name: Populate User Vectors

on:
  schedule:
    - cron: "*/20 * * * *"
  workflow_dispatch:

jobs:
  populate-vectors:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Supabase CLI
        run: npm install -g supabase

      - name: Run SQL via Supabase CLI
        run: supabase db execute -f supabase/sql/populate_user_vectors.sql
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
