name: Populate User Vectors

on:
  schedule:
    - cron: "*/20 * * * *"
  workflow_dispatch:

jobs:
  populate-vectors:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          npm init -y
          npm install node-fetch@3

      - name: Run SQL via Supabase API
        run: node scripts/run-sql.js
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
