name: Populate User Vectors

on:
  schedule:
    - cron: "*/20 * * * *" # Every 20 minutes
  workflow_dispatch:

jobs:
  populate-vectors:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Run SQL against Supabase
        run: |
          PGPASSWORD="${{ secrets.SUPABASE_DB_PASSWORD }}" \
          psql -h db.${{ secrets.SUPABASE_PROJECT_REF }}.supabase.co \
               -U postgres \
               -d postgres \
               -p 5432 \
               -f supabase/sql/populate_user_vectors.sql
